name: Deploy to GCP
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - id: checkout
        uses: actions/checkout@v4
        with:
          ref: refs/heads/master
          fetch-depth: 1

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('yarn.lock') }}

      - name: yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: yarn webpack
        uses: borales/actions-yarn@v4
        with:
          cmd: webpack

      - name: google auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: my-service-account@my-project.iam.gserviceaccount.com

      - name: upload-folders
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: dist
          destination: killiangrant.com
          parent: false
